name: Build Kernel
on:

  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest

jobs:
  yaml-check:
    runs-on: android
    permissions:
      contents: write
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
       node-version: 20

    - name: Imstall dependence
      run: cd tests && yarn install

    - name: Check yaml
      run: cd tests && node index.js

  ci-test:
    strategy:
      fail-fast: false
    needs:
      - yaml-check
    runs-on: android
    permissions:
      contents: write

    steps:
    - name: Test CI
      uses: Lukas0120/kernel_build_action@main
      with:
          kernel-url: https://github.com/DespairFactor/kernel_common
          kernel-dir: msm-4.19
          branch: main
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 14
          aosp-clang-version: r510928
          python-27: true
          disable-lto: false
          overlayfs: true
          lxc: false
          lxc-patch: false
          anykernel3: true
